project:
  type: book
  output-dir: docs

book:
  title: "RMS textbook"
  author: "Pilot, Lucas, and Murray"
  date: "10/28/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - fundamental_r_use.qmd
    - what_are_beh_sci.qmd
    - how_plan_exp.qmd
    - measure_behav.qmd
    - measurement.qmd
    - variability.qmd
    - select_participants.qmd
    - ethics.qmd
    - z_scores.qmd
    - probability.qmd
    - dist_sample_means.qmd
    - hyp_test.qmd
    - t_tests.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

